web_app/database/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from database.views import (store_view, cart_view,
                            checkout_view, update_item_view,
                            process_order_view)

app_name = 'database'
urlpatterns = [

    # Back end and Database urls
    path('store/', store_view, name='store'),
    path('cart/', cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('update_item/', update_item_view, name='update_item'),
    path('process_order/', process_order_view, name='process_order'),
]

urlpatterns += staticfiles_urlpatterns()

web_app/game/urls.py
from django.urls import include, path

from game.views import board_view

app_name = "game"
urlpatterns = [
    path('board', board_view, name='board'),
]

web_app/pages/urls.py
from django.urls import include, path

from .views import home_view, about_view, contact_view, projects_view

app_name = "pages"
urlpatterns = [
    path('home/', home_view, name='home'),
    path('', home_view),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('projects/', projects_view, name='projects'),
]

web_app/web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static, settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # Back end and Database urls
    path('database/', include('database.urls')),
    path('game/', include('game.urls')),
    path('', include('django.contrib.auth.urls')),
    # Front end
    path('', include('pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_app/templates/bases/base.html
{% load static %}
<!DOCTYPE HTML>
<html>

    <head>
        <title>Xadrez.pt-{% block title %}{% endblock %}</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'main.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        {% block head %}{% endblock head %}
    </head>

    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

            <div class="container navbar-brand">
                <img class="logo" src="{% static 'images/logo.jpg' %}" alt="logo">
            </div>
            <div class="mx-auto order-0">
                <a class="navbar-brand mx-auto" href="{% url 'pages:home' %}">ChessPowered.net</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'database:store' %}">Loja</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'database:cart' %}">Carrinho</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'game:board' %}">Play against machine</a>
                    </li>
                    {% if not user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    {% endif %}
                    <!-- {% if user.is_authenticated %} -->
                    <!-- <li class="nav-item"> -->
                    <!--     <a class="nav-link text-white" href="{% url 'logout' %}">Logout</a> -->
                    <!-- </li> -->
                    <!-- <li class="nav-item dropdown"> -->
                    <!--     <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
                    <!--         Base de dados -->
                    <!--     </a> -->
                    <!--     <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> -->
                    <!--         <a class="dropdown-item" href="#">list</a> -->
                    <!--         <a class="dropdown-item" href="#">Another action</a> -->
                    <!--         <a class="dropdown-item" href="#">Something else here</a> -->
                    <!--     </div> -->
                    <!-- </li> -->
                    <!-- {% endif %} -->

                </ul>
            </div>


            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        </nav>
    </header>

    <body>

        {% block content %}{% endblock content %}

        <script rel="text/javascript" src="{% static 'js/cart.js' %}"></script>
        <script rel="text/javascript">
         var user = "{{request.user}}"
         function getToken(name) {
             let cookieValue = null;
             if (document.cookie && document.cookie !== '') {
                 const cookies = document.cookie.split(';');
                 for (let i = 0; i < cookies.length; i++) {
                     const cookie = cookies[i].trim();
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) === (name + '=')) {
                         TokenValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return TokenValue;
         }
         const csrftoken = getToken('csrftoken');

        </script>
    </body>
</html>

web_app/templates/bases/footer.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/fontawesome.min.css' %}" />
</head>

<!-- Footer -->
<footer class="page-footer font-small bg-dark pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

<!-- Footer -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</footer>

web_app/templates/bases/game_base.html
{% load static %}
<!DOCTYPE HTML>
<html>

    <head>
        <title>Xadrez.pt-{% block title %}{% endblock %}</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'main.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        {% block head %}{% endblock head %}
    </head>

    <body>

        {% block content %}{% endblock content %}

        <script rel="text/javascript" src="{% static 'js/cart.js' %}"></script>
        <script rel="text/javascript">
         var user = "{{request.user}}"
         function getToken(name) {
             let cookieValue = null;
             if (document.cookie && document.cookie !== '') {
                 const cookies = document.cookie.split(';');
                 for (let i = 0; i < cookies.length; i++) {
                     const cookie = cookies[i].trim();
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) === (name + '=')) {
                         TokenValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return TokenValue;
         }
         const csrftoken = getToken('csrftoken');

        </script>
    </body>
</html>

web_app/templates/bases/navbar.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

        <div class="container navbar-brand">
            <img class="logo" src="{% static 'images/logo.jpg' %}" alt="logo">
        </div>
        <div class="mx-auto order-0">
            <a class="navbar-brand mx-auto" href="#">ChessPowered.net</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="#">Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Base de dados
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                {% endif %}

            </ul>
        </div>


        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </nav>
</header>