web_app/database/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from database.views import (store_view, cart_view,
                            checkout_view, update_item_view,
                            process_order_view)

app_name = 'database'
urlpatterns = [

    # Back end and Database urls
    path('store/', store_view, name='store'),
    path('cart/', cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('update_item/', update_item_view, name='update_item'),
    path('process_order/', process_order_view, name='process_order'),
]

urlpatterns += staticfiles_urlpatterns()

web_app/game/urls.py
from django.urls import include, path

from game.views import board_view

app_name = "game"
urlpatterns = [
    path('board', board_view, name='board'),
]

web_app/web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static, settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # Back end and Database urls
    path('database/', include('database.urls')),
    path('game/', include('game.urls')),
    path('', include('django.contrib.auth.urls')),
    # Front end
    path('', include('pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_app/database/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Customer(models.Model):
    "Represents a store customer"
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Product(models.Model):
    "Represents a store item in stock"
    name = models.CharField(max_length=200)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url

    def __str__(self):
        return self.name

class Order(models.Model):
    "Represents a cart of a user"
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    @property
    def get_cart_items(self):
        "Returns the number of items in the cart"
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    @property
    def get_cart_total(self):
        "Gets the total price of the cart"
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def shipping(self):
        "Returns if a order requires shipping"
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    "Represents a item that is in the cart of a user"
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        "Gets the total price of a cart item, according to its price and quantity"
        return self.product.price * self.quantity


class ShippingAddress(models.Model):
    "Represents a shipping adress of a user and a order"
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    zip_code = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    country = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.address

web_app/database/forms.py
from django import forms

# from .models import Client, Invoice


# class EditClientForm(forms.ModelForm):
#     nif = forms.CharField(
#         max_length=9,
#         label='Nif',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': '734231503',
#                 'class': 'form__input form__input--small',
#             }))

#     address = forms.CharField(
#         max_length=500,
#         label='Morada',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': 'Rua da carreira, edifício bela vista',
#                 'class': 'form__input',
#             }))

#     contact_email = forms.EmailField(
#         label='Email',
#         widget=forms.EmailInput(
#             attrs={
#                 'placeholder': 'ruiptbarros@gmail.com',
#                 'class': 'form__input',
#             }))

#     contact_phone = forms.CharField(
#         max_length=9,
#         label='Contacto',
#         widget=forms.TextInput(
#             attrs={
#                 'input': 'tel',
#                 'pattern': '[0-9]{9}',
#                 'placeholder': '921846856',
#                 'class': 'form__input form__input--small',
#             }))

#     zip_code = forms.CharField(
#         max_length=16,
#         label='Código Postal',
#         widget=forms.TextInput(
#             attrs={
#                 'pattern': '[0-9]{4}-[0-9]{3}',
#                 'placeholder': '9125-119',
#                 'class': 'form__input form__input--small',
#             }))

#     class Meta:
#         model = Client
#         fields = [
#             'nif',
#             'address',
#             'contact_email',
#             'contact_phone',
#             'zip_code',
#         ]


# class ClientForm(forms.ModelForm):
#     name = forms.CharField(
#         max_length=120,
#         label='Nome',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': 'Rui Barros (Max. 120 carácteres)',
#                 'class': 'form__input',
#             }))

#     nif = forms.CharField(
#         max_length=9,
#         label='Nif',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': '734231503',
#                 'class': 'form__input form__input--small',
#             }))

#     address = forms.CharField(
#         max_length=500,
#         label='Morada',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': 'Rua da carreira, edifício bela vista',
#                 'class': 'form__input',
#             }))

#     contact_email = forms.EmailField(
#         label='Email',
#         widget=forms.EmailInput(
#             attrs={
#                 'placeholder': 'ruiptbarros@gmail.com',
#                 'class': 'form__input',
#             }))

#     contact_phone = forms.CharField(
#         max_length=9,
#         label='Contacto',
#         widget=forms.TextInput(
#             attrs={
#                 'input': 'tel',
#                 'pattern': '[0-9]{9}',
#                 'placeholder': '921846856',
#                 'class': 'form__input form__input--small',
#             }))

#     zip_code = forms.CharField(
#         max_length=16,
#         label='Código Postal',
#         widget=forms.TextInput(
#             attrs={
#                 'pattern': '[0-9]{4}-[0-9]{3}',
#                 'placeholder': '9125-119',
#                 'class': 'form__input form__input--small',
#             }))

#     class Meta:
#         model = Client
#         fields = [
#             'name',
#             'nif',
#             'address',
#             'contact_email',
#             'contact_phone',
#             'zip_code',
#         ]


# class InvoiceForm(forms.ModelForm):
#     emission_date = forms.DateField(
#         label='Data de emissão',
#         widget=forms.DateInput(
#             attrs={
#                 'class': 'form__input form__input--small',
#                 'type': 'date',
#             }))

#     provider_name = forms.CharField(
#         max_length=120,
#         label='Nome do Provedor',
#         widget=forms.TextInput(
#             attrs={
#                 'value': 'Valter Pereira',
#                 'class': 'form__input form__input--small',
#             }))

#     provider_nif = forms.CharField(
#         max_length=9,
#         label='Nif do Provedor',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': '223345678',
#                 'class': 'form__input form__input--small',
#             }))
#     service_value = forms.DecimalField(
#         label='Valor do Serviço',
#         min_value=0,
#         decimal_places=2,
#         widget=forms.NumberInput(
#             attrs={
#                 'placeholder': '34.5',
#                 'class': 'form__input form__input--small',
#             }))

#     iva = forms.DecimalField(
#         required=False,
#         decimal_places=2,
#         max_digits=10,
#         min_value=0,
#         label='Taxa de Iva',
#         widget=forms.NumberInput(
#             attrs={
#                 'placeholder': '0.60',
#                 'class': 'form__input form__input--small',
#             }))

#     tax_explanation = forms.CharField(
#         label='Razão de isenção da taxa de Iva',
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'form__input form__input--textarea', }))

#     service_date = forms.DateField(
#         required=False,
#         label='Data de Serviço',
#         widget=forms.DateInput(
#             attrs={
#                 'type': 'date',
#                 'class': 'form__input form__input--small', }))

#     class Meta:
#         model = Invoice
#         fields = [
#             'client',
#             'emission_date',
#             'provider_name',
#             'provider_nif',
#             'service_value',
#             'iva',
#             'tax_explanation',
#             'service_date'
#         ]
#         labels = {
#             'name': 'Nome:',
#         }

web_app/database/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
import json
import datetime

from database.models import Product, Order, OrderItem, ShippingAddress
# from .forms import EditClientForm, ClientForm, InvoiceForm
# Create your views here.

def update_item_view(request):
    data = json.loads(request.body)
    productID = data['productID']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=productID)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    order_item, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == "add":
        order_item.quantity = (order_item.quantity + 1)
    elif action == "rem":
        order_item.quantity = (order_item.quantity - 1)

    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()


    return JsonResponse("Item as been added to the cart", safe=False)

def store_view(request):
    """ List all of the invoices """
    queryset = Product.objects.all()
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {
            'get_cart_total':0,
            'get_cart_items':0,
            'shipping': False
        }
        cartItems = order['get_cart_items']


    context = {
        'products': queryset,
        'order': order,
        'cartItems': cartItems
    }
    return render(request, 'database/store.html', context)

def cart_view(request):
    "This view delivers all of the products to be rendered on the page"

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {
            'get_cart_total':0,
            'get_cart_items':0,
            'shipping': False
        }
        cartItems = order['get_cart_items']


    context = {
        'products': items,
        'order': order,
        'cartItems': cartItems
    }

    return render(request, 'database/cart.html', context)

def checkout_view(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {
            'get_cart_total':0,
            'get_cart_items':0,
            'shipping': False
        }
        cartItems = order['get_cart_items']


    context = {
        'items': items,
        'order': order,
        'cartItems': cartItems
    }
    return render(request, 'database/checkout.html', context)

def process_order_view(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            zip_code=data['shipping']['zipcode'],
            country=data['shipping']['country'],
        )

    return JsonResponse('Payment complete', safe=False)

web_app/templates/database/cart.html
{% extends "bases/base.html" %}
{% load static %}
{% block title %} Carrinho {% endblock title %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
{% endblock head %}
{% block content %}
<div class="container pt-5">
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a  class="btn btn-outline-dark" href="{% url 'database:store' %}">&#x2190; Continue Shopping</a>
                <br>
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total:<strong>${{order.get_cart_total|floatformat:2}}</strong></h5></th>
                        <th>
                            <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'database:checkout' %}">Checkout</a>
                        </th>
                    </tr>
                </table>
            </div>

            <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>

                {% for product in products %}
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{{product.product.imageURL}}"></div>
                    <div style="flex:2"><p>{{product.product.name}}</p></div>
                    <div style="flex:1"><p>{{product.product.price|floatformat:2}}</p></div>
                    <div style="flex:1">
                        <p class="quantity">{{product.quantity}}</p>
                        <div class="quantity">
                            <img data-attribute="{{product.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow_up.png' %}">

                            <img data-attribute="{{product.product.id}}" data-action="rem" class="chg-quantity rotate-image update-cart" src="{% static  'images/arrow_up.png' %}">
                        </div>
                    </div>
                    <div style="flex:1"><p>{{product.get_total|floatformat:2}}</p></div>
                </div>
                {% endfor %}
            </div>
        </div>
</div></div>
</div>
{% endblock content %}

web_app/templates/database/checkout.html
{% extends "bases/base.html" %}
{% load static %}
{% block title %}
Checkout
{% endblock title %}
{% block head %}
{% endblock head %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">{% csrf_token %}
                    {% if not user.is_authenticated  %}
                    <div id="user-info">
                        <div class="form-field">
                            <input required class="form-control" type="text" name="name" placeholder="Name..">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="email" name="email" placeholder="Email..">
                        </div>
                    </div>
                    {% endif %}
                    {% if order.shipping %}
                    <div id="shipping-info">
                        <hr>
                        <p>Shipping Information:</p>
                        <hr>
                        <div class="form-field">
                            <input class="form-control" type="text" name="address" placeholder="Address..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="city" placeholder="City..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="country" placeholder="Country..">
                        </div>
                    </div>
                    {% endif %}
                    <hr>
                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
                </form>
            </div>

        </div>

        <div class="col-lg-6">
            <div class="box-element">
                <a  class="btn btn-outline-dark" href="{% url 'database:cart' %}">&#x2190; Back to Cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for item in items %}
                <div class="cart-row">
                    <!-- These flex styles change the behaviour of the page on changing, the bigger it is
                         the bigger it will be when it shrinks -->
                    <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                    <div style="flex:2"><p>{{item.product.name}}</p></div>
                    <div style="flex:1"><p>{{item.product.price|floatformat:2}}</p></div>
                    <div style="flex:1"><p class="quantity">x{{item.quantity}}</p> </div>
                </div>
                {% endfor %}
                <h5>Items:  {{order.get_cart_items}} </h5>
                <h5>Total:  {{order.get_cart_total|floatformat:2}}</h5>
            </div>
        </div>
    </div>
    <br>
    <div class="box-element hidden" id="payment-info">
        <small>Paypal Options</small>
        <button id="make-payment">

        </button>
    </div>
</div>

<script type="text/javascript">
 var total = "{{order.get_cart_total}}"
 var shipping = "{{order.shipping}}"

 var form = document.getElementById('form')
 form.addEventListener('submit', function(e){

     // This is to block the button to do it's default stuff aka request post
     e.preventDefault()

     console.log('Form Submitted...')

     // Changes the css classes of these elements to add or remove hidden property
     document.getElementById('form-button').classList.add("hidden")
     document.getElementById('payment-info').classList.remove("hidden")

     document.getElementById('make-payment').addEventListener('click', function(e){
         submitFormData()})
     function submitFormData(){
         console.log('Payment button clicked')

         var user = "{{request.user}}"
         var userFormData = {
             'name': null,
             'email':null,
             'total': total
         }
         var shippingInfo = {
             'address': null,
             'city': null,
             'zipcode':null,
             'country':null
         }
         if(shipping != 'False'){
             shippingInfo.address = form.address.value
             shippingInfo.city = form.city.value
             shippingInfo.zipcode = form.zipcode.value
             shippingInfo.country = form.country.value
         }

         if(user == "AnonymousUser") {
             userFormData.name = form.name.value
             userFormData.email = form.email.value
         }
    var url = '/database/process_order/'

     fetch(url, {
         method: 'POST', headers: {
             'Content-Type':'application/json',
             'X-CSRFToken': csrftoken,
         },
         body: JSON.stringify({
             'form': userFormData,
             'shipping': shippingInfo
     })})
     // When the asynchronous call above completes, these guys are called only once
         .then((response) => {
             return response.json()
         })
     // This only gets called if the above response is executed
         .then((data) => {
             console.log('Success:', data)
             window.location.href = "{% url 'database:store' %}"
         })

 }
 })
</script>

{% endblock content %}

web_app/templates/database/store.html
{% extends "bases/base.html" %}
{% load static %}
{% block title %}
<title>Loja</title>
{% endblock title %}
{% block head %}
{% endblock head %}
{% block content %}
<div class="container pt-5">
  <div class="row">
    {% for product in products %}
    <div class="col-lg-4">
      <img class="thumbnail" src="{{product.imageURL}}">
      <div class="box-element product">
        <h8><strong>{{product.name}}</strong></h8>
        <hr>
        <button data-attribute="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
        <a class="btn btn-outline-success" href="%">View</a>
        <h4 style="display: inline-block; float: right"><strong>${{product.price|floatformat:2}}</strong></h4>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
{% endblock content %}